# See http://dev.bukkit.org/server-mods/portablehole/pages/configuration

#
# List of block ids to whitelist/blacklist, overriding the plugin's internal list
# Whitelisted blocks will always be tunnellable - be careful what you add to this list!
# Blacklisted blocks will always cause tunnel creation to fail if they're encountered
tunnellable:
  whitelist: []
  blacklist: [ 23, 54, 58, 61, 62, 95, 116, 117, 118 ]

#
# List of costs for creating a hole, and the length of tunnel each cost will allow
# The first cost in the list that is affordable by the player will be applied/
# Note that at most one cost from the list will be applied.
costs:
  # Consuming one redstone will give the player credit to tunnel 20 blocks
  - cost: REDSTONE
    blocks: 20
  # Consuming one coal will give the player credit to tunnel 10 blocks
  - cost: COAL
    blocks: 10
  # Spending one economy credit will allow one block to be tunnelled
  - cost: E,1
  # Applying 1 damage to a diamond pick (use negative block id to specify durability cost)
  # will allow one block to be tunnelled
  - cost: DIAMOND_PICKAXE,1,D
  # Applying 1 health damage to the player allows one block to be tunnelled
  - cost: H,1

# 
# Define which players and/or permission groups can own books that can be used to tunnel.
# If players and groups are both blank, then anyone's books can be used.
# Otherwise, if the book's author is in the player list, the book can be used.
# Otherwise, if the book's author is in a group in the groups list, the book can be used.
# Otherwise, the book cannot be used.
# Vault and a valid permissions plugin must be present for group checking to be used.
author_validation:
  players: [ ]
  groups: [ ]

#
# Effects that get played when holes are opened/closed
# Set to blank to play no sound
effects:
  hole_open: sound,name=enderman_teleport
  hole_close: sound,name=enderman_teleport
  hole_failed: sound,name=note_bass
  
# Show particle effect within the hole, diminishing as the hole ages
# Use any *visual* effect from http://jd.bukkit.org/apidocs/org/bukkit/Effect.html)
# Leave blank for no particle effect
particle_effect: ender_signal

# Hole lifetime control - values are in ticks
# Total hole lifetime = initial + (hole-length * per_length)
lifetime:
  initial: 15
  per_length: 20

# Logging level (can be FINEST, FINER, FINE, INFO, WARNING, SEVERE - case insensitive)
# Leave at INFO normally 
log_level: INFO

# Books must have this title to be considered for hole creation
book_title: Portable Hole

# Default book text for books create with /ph give
default_book_text:
  - Portable Hole
  -
  - Left-click to use!

# Message the player about any costs taken from them
verbose_charges: true

# Prevent players from opening tunnels into the void
void_tunnelling: false

# Maximum length a tunnel can be
max_tunnel_length:
  horizontal: 31
  vertical: 31

#
# Message text
messages:
  cant_create: Can't create a hole here.
  too_deep: Can't create a hole that deep.
  stopped: Something prevents you from tunnelling here...
  cant_afford: Can't afford to dig!
  credits: You have %d tunnelling credits.
  gave_book: "Gave a %s book to &e%s."
  got_book: "You have been given a %s book."
  not_valid_author: The author of this book isn't allowed to create holes.
  charge_made: "Tunnelling charge taken: &e%s"

#
# Book crafting configuration
crafting:
  # is crafting enabled at all?
  enabled: true
  # shaped or shapeless recipe?
  shaped: true
  # the recipe: for shaped, a list of 1-3 rows, each row with 1-3 letters
  #  for shapeless, a list of 1-9 materials in any order
  recipe: [ " E ", "RBR", " E " ]
  # the ingredients: map a letter in the recipe to a material
  ingredients:
    E: ENDER_PEARL
    B: BOOK
    R: REDSTONE
  # the author of any crafted books (empty means the crafting player will be author)
  # you might want to set this to a different player if you use author_validation (see above)
  author: ""
